dependencies-cache-key: &dependencies-cache-key dependencies--{{ checksum "Gemfile.lock" }}-{{ checksum "Podfile.lock" }}

version: 2
jobs:
  dependencies:
    macos:
      xcode: "13.2.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_PATH: vendor/bundle
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          key: *dependencies-cache-key
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install --jobs 4 --retry 3
      - run:
          name: Install Cocoapods dependencies
          command: |
              bundle exec pod install
              diff ./Podfile.lock ./Pods/Manifest.lock > /dev/null || pod_install
      - save_cache:
          key: *dependencies-cache-key
          paths:
            - vendor/bundle/
            - Pods/
  lint:
    macos:
      xcode: "13.2.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_PATH: vendor/bundle
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          key: *dependencies-cache-key
      # Some different versions are installed on the Xcode 10 server, so we need to re-install ruby gems.
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install --jobs 4 --retry 3
      - run:
          name: Install Cocoapods dependencies
          command: |
              bundle exec pod install
              diff ./Podfile.lock ./Pods/Manifest.lock > /dev/null || pod_install
      - run: bundle exec fastlane lint
  test-xcode13:
    macos:
      xcode: "13.2.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      BUNDLE_PATH: vendor/bundle
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          key: *dependencies-cache-key
      - run: xcodebuild -sdk -version
      # Some different versions are installed on the Xcode 10 server, so we need to re-install ruby gems.
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install --jobs 4 --retry 3
      - run: bundle exec fastlane test_carthage
      - run: FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 bundle exec fastlane test_latest_xcode --verbose

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test-xcode13:
          requires:
            - dependencies
